import type { Metadata } from 'next';

type RootLayoutArgs = Readonly<{
	children: React.ReactNode;
}>;

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutArgs) {
	return (
		<html>
			<head>
				<script src="https://www.google.com/recaptcha/api.js?render=6LeLaQgqAAAAAAoShIb8NWKtYYY9mm5kVJstwy5H"></script>
			</head>
			<body>{children}</body>
		</html>
	);
}
