name: Publish New Version

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
            RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
            DATABASE_URI: 'mongodb://127.0.0.1/payload-recaptcha-v3'
        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v4
              with:
                  version: '9.15.0'
                  run_install: false
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm build
            - run: pnpm dev:build
            - uses: supercharge/mongodb-github-action@1.11.0
              with:
                  mongodb-version: '7.0'
            - run: pnpm exec playwright install
            - run: pnpm test
            - run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
